language: node_js
node_js:
  - 10
  - 11
  - 12
  - 13
before_install:
  - npm install -g yarn
matrix:
  - TSX=1
  - TSX=0
script:
  - if [ "$TSX" == 0 ]; then yarn lint
  - if [ "$TSX" == 0 ]; then yarn test
  - if [ "$TSX" == 0 ]; then yarn docs
  - if [ "$TSX" == 0 ]; then yarn docs
  - if [ "$TSX" == 0 ]; then yarn validate-translations
  - if [ "$TSX" == 1 ]; then tsc --strict
